const arr=[
	{y:0,audioname:"audiozero",file:'./audio/audiozero.wav'},
	{y:1,audioname:"audiozero",file:'./audio/audiozero.wav'},
	{y:2,audioname:"audiozero",file:'./audio/audiozero.wav'},
	{y:3,audioname:"audiozero",file:'./audio/audiozero.wav'},
	{y:4,audioname:"audiozero",file:'./audio/audiozero.wav'},
	{y:5,audioname:"audiozero",file:'./audio/audiozero.wav'},
	{y:6,audioname:"audioone",file:'./audio/audioone.wav'},
	{y:7,audioname:"audioone",file:'./audio/audioone.wav'},
	{y:8,audioname:"audioone",file:'./audio/audioone.wav'},
	{y:9,audioname:"audioone",file:'./audio/audioone.wav'},
	{y:10,audioname:"audioone",file:'./audio/audioone.wav'},
	{y:11,audioname:"audiotwo",file:'./audio/audiotwo.wav'},
	{y:12,audioname:"audiotwo",file:'./audio/audiotwo.wav'},
	{y:13,audioname:"audiotwo",file:'./audio/audiotwo.wav'},
	{y:14,audioname:"audiotwo",file:'./audio/audiotwo.wav'},
	{y:15,audioname:"audiotwo",file:'./audio/audiotwo.wav'},
	{y:16,audioname:"audiothree",file:'./audio/audiothree.wav'},
	{y:17,audioname:"audiothree",file:'./audio/audiothree.wav'},
	{y:18,audioname:"audiothree",file:'./audio/audiothree.wav'},
	{y:19,audioname:"audiothree",file:'./audio/audiothree.wav'},
	{y:20,audioname:"audiothree",file:'./audio/audiothree.wav'},
	{y:21,audioname:"audiofour",file:'./audio/audiofour.wav'},
	{y:22,audioname:"audiofour",file:'./audio/audiofour.wav'},
	{y:23,audioname:"audiofour",file:'./audio/audiofour.wav'},
	{y:24,audioname:"audiofour",file:'./audio/audiofour.wav'},
	{y:25,audioname:"audiofour",file:'./audio/audiofour.wav'},
	{y:26,audioname:"audiofive",file:'./audio/audiofive.wav'},
	{y:27,audioname:"audiofive",file:'./audio/audiofive.wav'},
	{y:28,audioname:"audiofive",file:'./audio/audiofive.wav'},
	{y:29,audioname:"audiofive",file:'./audio/audiofive.wav'},
	{y:30,audioname:"audiofive",file:'./audio/audiofive.wav'},
	{y:31,audioname:"audiosix",file:'./audio/audiosix.wav'},
	{y:32,audioname:"audiosix",file:'./audio/audiosix.wav'},
	{y:33,audioname:"audiosix",file:'./audio/audiosix.wav'},
	{y:34,audioname:"audiosix",file:'./audio/audiosix.wav'},
	{y:35,audioname:"audiosix",file:'./audio/audiosix.wav'},
	{y:36,audioname:"audioseven",file:'./audio/audioseven.wav'},
	{y:37,audioname:"audioseven",file:'./audio/audioseven.wav'},
	{y:38,audioname:"audioseven",file:'./audio/audioseven.wav'},
	{y:39,audioname:"audioseven",file:'./audio/audioseven.wav'},
	{y:40,audioname:"audioseven",file:'./audio/audioseven.wav'},
	{y:41,audioname:"audioeight",file:'./audio/audioeight.wav'},
	{y:42,audioname:"audioeight",file:'./audio/audioeight.wav'},
	{y:43,audioname:"audioeight",file:'./audio/audioeight.wav'},
	{y:44,audioname:"audioeight",file:'./audio/audioeight.wav'},
	{y:45,audioname:"audioeight",file:'./audio/audioeight.wav'},
	{y:46,audioname:"audionine",file:'./audio/audionine.wav'},
	{y:47,audioname:"audionine",file:'./audio/audionine.wav'},
	{y:48,audioname:"audionine",file:'./audio/audionine.wav'},
	{y:49,audioname:"audionine",file:'./audio/audionine.wav'},
	{y:50,audioname:"audionine",file:'./audio/audionine.wav'},
	{y:51,audioname:"audio11",file:'./audio/audio11.wav'},
	{y:52,audioname:"audio11",file:'./audio/audio11.wav'},
	{y:53,audioname:"audio11",file:'./audio/audio11.wav'},
	{y:54,audioname:"audio11",file:'./audio/audio11.wav'},
	{y:55,audioname:"audio11",file:'./audio/audio11.wav'},
	{y:56,audioname:"audio12",file:'./audio/audio12.wav'},
	{y:57,audioname:"audio12",file:'./audio/audio12.wav'},
	{y:58,audioname:"audio12",file:'./audio/audio12.wav'},
	{y:59,audioname:"audio12",file:'./audio/audio12.wav'},
	{y:60,audioname:"audio12",file:'./audio/audio12.wav'},
	{y:61,audioname:"audio13",file:'./audio/audio13.wav'},
	{y:62,audioname:"audio13",file:'./audio/audio13.wav'},
	{y:63,audioname:"audio13",file:'./audio/audio13.wav'},
	{y:64,audioname:"audio13",file:'./audio/audio13.wav'},
	{y:65,audioname:"audio13",file:'./audio/audio13.wav'},
	{y:66,audioname:"audio14",file:'./audio/audio14.wav'},
	{y:67,audioname:"audio14",file:'./audio/audio14.wav'},
	{y:68,audioname:"audio14",file:'./audio/audio14.wav'},
	{y:69,audioname:"audio14",file:'./audio/audio14.wav'},
	{y:70,audioname:"audio14",file:'./audio/audio14.wav'},
	{y:71,audioname:"audio15",file:'./audio/audio15.wav'},
	{y:72,audioname:"audio15",file:'./audio/audio15.wav'},
	{y:73,audioname:"audio15",file:'./audio/audio15.wav'},
	{y:74,audioname:"audio15",file:'./audio/audio15.wav'},
	{y:75,audioname:"audio15",file:'./audio/audio15.wav'},
	{y:76,audioname:"audio16",file:'./audio/audio16.wav'},
	{y:77,audioname:"audio16",file:'./audio/audio16.wav'},
	{y:78,audioname:"audio16",file:'./audio/audio16.wav'},
	{y:79,audioname:"audio16",file:'./audio/audio16.wav'},
	{y:80,audioname:"audio16",file:'./audio/audio16.wav'},
	{y:81,audioname:"audio17",file:'./audio/audio17.wav'},
	{y:82,audioname:"audio17",file:'./audio/audio17.wav'},
	{y:83,audioname:"audio17",file:'./audio/audio17.wav'},
	{y:84,audioname:"audio17",file:'./audio/audio17.wav'},
	{y:85,audioname:"audio17",file:'./audio/audio17.wav'},
	{y:86,audioname:"audio18",file:'./audio/audio17.wav'},
	{y:87,audioname:"audio18",file:'./audio/audio18.wav'},
	{y:88,audioname:"audio18",file:'./audio/audio18.wav'},
	{y:89,audioname:"audio18",file:'./audio/audio18.wav'},
	{y:90,audioname:"audio18",file:'./audio/audio18.wav'},
	{y:91,audioname:"audio19",file:'./audio/audio19.wav'},
	{y:92,audioname:"audio19",file:'./audio/audio19.wav'},
	{y:93,audioname:"audio19",file:'./audio/audio19.wav'},
	{y:94,audioname:"audio19",file:'./audio/audio19.wav'},
	{y:95,audioname:"audio19",file:'./audio/audio19.wav'},
	{y:96,audioname:"audio20",file:'./audio/audio20.wav'},
	{y:97,audioname:"audio20",file:'./audio/audio20.wav'},
	{y:98,audioname:"audio20",file:'./audio/audio20.wav'},
	{y:99,audioname:"audio20",file:'./audio/audio20.wav'},
	{y:100,audioname:"audio20",file:'./audio/audio20.wav'},


	{y:101,audioname:"audioone",file:'./audio/audioone.wav'},
	{y:102,audioname:"audiotwo",file:'./audio/audiotwo.wav'},
	{y:103,audioname:"audiothree",file:'./audio/audiothree.wav'},
	{y:104,audioname:"audiofour",file:'./audio/audiofour.wav'},
	{y:105,audioname:"audiofive",file:'./audio/audiofive.wav'},
	{y:106,audioname:"audiosix",file:'./audio/audiosix.wav'},
	{y:107,audioname:"audioseven",file:'./audio/audioseven.wav'},
	{y:108,audioname:"audioeight",file:'./audio/audioeight.wav'},
	{y:109,audioname:"audionine",file:'./audio/audionine.wav'},
	{y:110,audioname:"audioten",file:'./audio/audioten.wav'},
	{y:111,audioname:"audio11",file:'./audio/audio11.wav'},
	{y:112,audioname:"audio12",file:'./audio/audio12.wav'},
	{y:113,audioname:"audio13",file:'./audio/audio13.wav'},
	{y:114,audioname:"audio14",file:'./audio/audio14.wav'},
	{y:115,audioname:"audio15",file:'./audio/audio15.wav'},
	{y:116,audioname:"audio16",file:'./audio/audio16.wav'},
	{y:117,audioname:"audio17",file:'./audio/audio17.wav'},
	{y:118,audioname:"audio18",file:'./audio/audio18.wav'},
	{y:119,audioname:"audio19",file:'./audio/audio19.wav'},
	{y:120,audioname:"audio20",file:'./audio/audio20.wav'},
	{y:121,audioname:"audio21",file:'./audio/audio21.wav'},
	{y:122,audioname:"audiotwo",file:'./audio/audiotwo.wav'},
	{y:123,audioname:"audiothree",file:'./audio/audiothree.wav'},
	{y:124,audioname:"audiofour",file:'./audio/audiofour.wav'},
	{y:125,audioname:"audiofive",file:'./audio/audiofive.wav'},
	{y:126,audioname:"audiosix",file:'./audio/audiosix.wav'},
	{y:127,audioname:"audioseven",file:'./audio/audioseven.wav'},
	{y:128,audioname:"audioeight",file:'./audio/audioeight.wav'},
	{y:129,audioname:"audionine",file:'./audio/audionine.wav'},
	{y:130,audioname:"audioten",file:'./audio/audioten.wav'},
	{y:131,audioname:"audioone",file:'./audio/audioone.wav'},
	{y:132,audioname:"audiotwo",file:'./audio/audiotwo.wav'},
	{y:133,audioname:"audiothree",file:'./audio/audiothree.wav'},
	{y:134,audioname:"audiofour",file:'./audio/audiofour.wav'},
	{y:135,audioname:"audiofive",file:'./audio/audiofive.wav'},
	{y:136,audioname:"audiosix",file:'./audio/audiosix.wav'},
	{y:137,audioname:"audioseven",file:'./audio/audioseven.wav'},
	{y:138,audioname:"audioeight",file:'./audio/audioeight.wav'},
	{y:139,audioname:"audionine",file:'./audio/audionine.wav'},
	{y:140,audioname:"audioten",file:'./audio/audioten.wav'},
	{y:141,audioname:"audio11",file:'./audio/audio11.wav'},
	{y:142,audioname:"audio12",file:'./audio/audio12.wav'},
	{y:143,audioname:"audio13",file:'./audio/audio13.wav'},
	{y:144,audioname:"audio14",file:'./audio/audio14.wav'},
	{y:145,audioname:"audio15",file:'./audio/audio15.wav'},
	{y:146,audioname:"audio16",file:'./audio/audio16.wav'},
	{y:147,audioname:"audio17",file:'./audio/audio17.wav'},
	{y:148,audioname:"audio18",file:'./audio/audio18.wav'},
	{y:149,audioname:"audio19",file:'./audio/audio19.wav'},
	{y:150,audioname:"audio20",file:'./audio/audio20.wav'},
	{y:151,audioname:"audioone",file:'./audio/audioone.wav'},
	{y:152,audioname:"audiotwo",file:'./audio/audiotwo.wav'},
	{y:153,audioname:"audiothree",file:'./audio/audiothree.wav'},
	{y:154,audioname:"audiofour",file:'./audio/audiofour.wav'},
	{y:155,audioname:"audiofive",file:'./audio/audiofive.wav'},
	{y:156,audioname:"audiosix",file:'./audio/audiosix.wav'},
	{y:157,audioname:"audioseven",file:'./audio/audioseven.wav'},
	{y:158,audioname:"audioeight",file:'./audio/audioeight.wav'},
	{y:159,audioname:"audionine",file:'./audio/audionine.wav'},
	{y:160,audioname:"audioten",file:'./audio/audioten.wav'},
	{y:161,audioname:"audio11",file:'./audio/audio11.wav'},
	{y:162,audioname:"audio12",file:'./audio/audio12.wav'},
	{y:163,audioname:"audio13",file:'./audio/audio13.wav'},
	{y:164,audioname:"audio14",file:'./audio/audio14.wav'},
	{y:165,audioname:"audio15",file:'./audio/audio15.wav'},
	{y:166,audioname:"audio16",file:'./audio/audio16.wav'},
	{y:167,audioname:"audio17",file:'./audio/audio17.wav'},
	{y:168,audioname:"audio18",file:'./audio/audio18.wav'},
	{y:169,audioname:"audio19",file:'./audio/audio19.wav'},
	{y:170,audioname:"audio20",file:'./audio/audio20.wav'},
	{y:171,audioname:"audio21",file:'./audio/audio21.wav'},
	{y:172,audioname:"audiotwo",file:'./audio/audiotwo.wav'},
	{y:173,audioname:"audiothree",file:'./audio/audiothree.wav'},
	{y:174,audioname:"audiofour",file:'./audio/audiofour.wav'},
	{y:175,audioname:"audiofive",file:'./audio/audiofive.wav'},
	{y:176,audioname:"audiosix",file:'./audio/audiosix.wav'},
	{y:177,audioname:"audioseven",file:'./audio/audioseven.wav'},
	{y:178,audioname:"audioeight",file:'./audio/audioeight.wav'},
	{y:179,audioname:"audionine",file:'./audio/audionine.wav'},
	{y:180,audioname:"audioten",file:'./audio/audioten.wav'},
	{y:181,audioname:"audioone",file:'./audio/audioone.wav'},
	{y:182,audioname:"audiotwo",file:'./audio/audiotwo.wav'},
	{y:183,audioname:"audiothree",file:'./audio/audiothree.wav'},
	{y:184,audioname:"audiofour",file:'./audio/audiofour.wav'},
	{y:185,audioname:"audiofive",file:'./audio/audiofive.wav'},
	{y:186,audioname:"audiosix",file:'./audio/audiosix.wav'},
	{y:187,audioname:"audioseven",file:'./audio/audioseven.wav'},
	{y:188,audioname:"audioeight",file:'./audio/audioeight.wav'},
	{y:189,audioname:"audionine",file:'./audio/audionine.wav'},
	{y:190,audioname:"audioten",file:'./audio/audioten.wav'},
	{y:191,audioname:"audio11",file:'./audio/audio11.wav'},
	{y:192,audioname:"audio12",file:'./audio/audio12.wav'},
	{y:193,audioname:"audio13",file:'./audio/audio13.wav'},
	{y:194,audioname:"audio14",file:'./audio/audio14.wav'},
	{y:195,audioname:"audio15",file:'./audio/audio15.wav'},
	{y:196,audioname:"audio16",file:'./audio/audio16.wav'},
	{y:197,audioname:"audio17",file:'./audio/audio17.wav'},
	{y:198,audioname:"audio18",file:'./audio/audio18.wav'},
	{y:199,audioname:"audio19",file:'./audio/audio19.wav'},
	{y:200,audioname:"audio20",file:'./audio/audio20.wav'},


	
	{y:201,audioname:"audioone",file:'./audio/audioone.wav'},
	{y:202,audioname:"audiotwo",file:'./audio/audiotwo.wav'},
	{y:203,audioname:"audiothree",file:'./audio/audiothree.wav'},
	{y:204,audioname:"audiofour",file:'./audio/audiofour.wav'},
	{y:205,audioname:"audiofive",file:'./audio/audiofive.wav'},
	{y:206,audioname:"audiosix",file:'./audio/audiosix.wav'},
	{y:207,audioname:"audioseven",file:'./audio/audioseven.wav'},
	{y:208,audioname:"audioeight",file:'./audio/audioeight.wav'},
	{y:209,audioname:"audionine",file:'./audio/audionine.wav'},
	{y:210,audioname:"audioten",file:'./audio/audioten.wav'},
	{y:211,audioname:"audio11",file:'./audio/audio11.wav'},
	{y:212,audioname:"audio12",file:'./audio/audio12.wav'},
	{y:213,audioname:"audio13",file:'./audio/audio13.wav'},
	{y:214,audioname:"audio14",file:'./audio/audio14.wav'},
	{y:215,audioname:"audio15",file:'./audio/audio15.wav'},
	{y:216,audioname:"audio16",file:'./audio/audio16.wav'},
	{y:217,audioname:"audio17",file:'./audio/audio17.wav'},
	{y:218,audioname:"audio18",file:'./audio/audio18.wav'},
	{y:219,audioname:"audio19",file:'./audio/audio19.wav'},
	{y:220,audioname:"audio20",file:'./audio/audio20.wav'},
	{y:221,audioname:"audio21",file:'./audio/audio21.wav'},
	{y:222,audioname:"audiotwo",file:'./audio/audiotwo.wav'},
	{y:223,audioname:"audiothree",file:'./audio/audiothree.wav'},
	{y:224,audioname:"audiofour",file:'./audio/audiofour.wav'},
	{y:225,audioname:"audiofive",file:'./audio/audiofive.wav'},
	{y:226,audioname:"audiosix",file:'./audio/audiosix.wav'},
	{y:227,audioname:"audioseven",file:'./audio/audioseven.wav'},
	{y:228,audioname:"audioeight",file:'./audio/audioeight.wav'},
	{y:229,audioname:"audionine",file:'./audio/audionine.wav'},
	{y:230,audioname:"audioten",file:'./audio/audioten.wav'},
	{y:231,audioname:"audioone",file:'./audio/audioone.wav'},
	{y:232,audioname:"audiotwo",file:'./audio/audiotwo.wav'},
	{y:233,audioname:"audiothree",file:'./audio/audiothree.wav'},
	{y:234,audioname:"audiofour",file:'./audio/audiofour.wav'},
	{y:235,audioname:"audiofive",file:'./audio/audiofive.wav'},
	{y:236,audioname:"audiosix",file:'./audio/audiosix.wav'},
	{y:237,audioname:"audioseven",file:'./audio/audioseven.wav'},
	{y:238,audioname:"audioeight",file:'./audio/audioeight.wav'},
	{y:239,audioname:"audionine",file:'./audio/audionine.wav'},
	{y:240,audioname:"audioten",file:'./audio/audioten.wav'},
	{y:241,audioname:"audio11",file:'./audio/audio11.wav'},
	{y:242,audioname:"audio12",file:'./audio/audio12.wav'},
	{y:243,audioname:"audio13",file:'./audio/audio13.wav'},
	{y:244,audioname:"audio14",file:'./audio/audio14.wav'},
	{y:245,audioname:"audio15",file:'./audio/audio15.wav'},
	{y:246,audioname:"audio16",file:'./audio/audio16.wav'},
	{y:247,audioname:"audio17",file:'./audio/audio17.wav'},
	{y:248,audioname:"audio18",file:'./audio/audio18.wav'},
	{y:249,audioname:"audio19",file:'./audio/audio19.wav'},
	{y:250,audioname:"audio20",file:'./audio/audio20.wav'},
	{y:251,audioname:"audioone",file:'./audio/audioone.wav'},
	{y:252,audioname:"audiotwo",file:'./audio/audiotwo.wav'},
	{y:253,audioname:"audiothree",file:'./audio/audiothree.wav'},
	{y:254,audioname:"audiofour",file:'./audio/audiofour.wav'},
	{y:255,audioname:"audiofive",file:'./audio/audiofive.wav'},
	{y:256,audioname:"audiosix",file:'./audio/audiosix.wav'},
	{y:257,audioname:"audioseven",file:'./audio/audioseven.wav'},
	{y:258,audioname:"audioeight",file:'./audio/audioeight.wav'},
	{y:259,audioname:"audionine",file:'./audio/audionine.wav'},
	{y:260,audioname:"audioten",file:'./audio/audioten.wav'},
	{y:261,audioname:"audio11",file:'./audio/audio11.wav'},
	{y:262,audioname:"audio12",file:'./audio/audio12.wav'},
	{y:263,audioname:"audio13",file:'./audio/audio13.wav'},
	{y:264,audioname:"audio14",file:'./audio/audio14.wav'},
	{y:265,audioname:"audio15",file:'./audio/audio15.wav'},
	{y:266,audioname:"audio16",file:'./audio/audio16.wav'},
	{y:267,audioname:"audio17",file:'./audio/audio17.wav'},
	{y:268,audioname:"audio18",file:'./audio/audio18.wav'},
	{y:269,audioname:"audio19",file:'./audio/audio19.wav'},
	{y:270,audioname:"audio20",file:'./audio/audio20.wav'},
	{y:271,audioname:"audio21",file:'./audio/audio21.wav'},
	{y:272,audioname:"audiotwo",file:'./audio/audiotwo.wav'},
	{y:273,audioname:"audiothree",file:'./audio/audiothree.wav'},
	{y:274,audioname:"audiofour",file:'./audio/audiofour.wav'},
	{y:275,audioname:"audiofive",file:'./audio/audiofive.wav'},
	{y:276,audioname:"audiosix",file:'./audio/audiosix.wav'},
	{y:277,audioname:"audioseven",file:'./audio/audioseven.wav'},
	{y:278,audioname:"audioeight",file:'./audio/audioeight.wav'},
	{y:279,audioname:"audionine",file:'./audio/audionine.wav'},
	{y:280,audioname:"audioten",file:'./audio/audioten.wav'},
	{y:281,audioname:"audioone",file:'./audio/audioone.wav'},
	{y:282,audioname:"audiotwo",file:'./audio/audiotwo.wav'},
	{y:283,audioname:"audiothree",file:'./audio/audiothree.wav'},
	{y:284,audioname:"audiofour",file:'./audio/audiofour.wav'},
	{y:285,audioname:"audiofive",file:'./audio/audiofive.wav'},
	{y:286,audioname:"audiosix",file:'./audio/audiosix.wav'},
	{y:287,audioname:"audioseven",file:'./audio/audioseven.wav'},
	{y:288,audioname:"audioeight",file:'./audio/audioeight.wav'},
	{y:289,audioname:"audionine",file:'./audio/audionine.wav'},
	{y:290,audioname:"audioten",file:'./audio/audioten.wav'},
	{y:291,audioname:"audio11",file:'./audio/audio11.wav'},
	{y:292,audioname:"audio12",file:'./audio/audio12.wav'},
	{y:293,audioname:"audio13",file:'./audio/audio13.wav'},
	{y:294,audioname:"audio14",file:'./audio/audio14.wav'},
	{y:295,audioname:"audio15",file:'./audio/audio15.wav'},
	{y:296,audioname:"audio16",file:'./audio/audio16.wav'},
	{y:297,audioname:"audio17",file:'./audio/audio17.wav'},
	{y:298,audioname:"audio18",file:'./audio/audio18.wav'},
	{y:299,audioname:"audio19",file:'./audio/audio19.wav'},
	{y:300,audioname:"audio20",file:'./audio/audio20.wav'},

	
	{y:301,audioname:"audioone",file:'./audio/audioone.wav'},
	{y:302,audioname:"audiotwo",file:'./audio/audiotwo.wav'},
	{y:303,audioname:"audiothree",file:'./audio/audiothree.wav'},
	{y:304,audioname:"audiofour",file:'./audio/audiofour.wav'},
	{y:305,audioname:"audiofive",file:'./audio/audiofive.wav'},
	{y:306,audioname:"audiosix",file:'./audio/audiosix.wav'},
	{y:307,audioname:"audioseven",file:'./audio/audioseven.wav'},
	{y:308,audioname:"audioeight",file:'./audio/audioeight.wav'},
	{y:309,audioname:"audionine",file:'./audio/audionine.wav'},
	{y:310,audioname:"audioten",file:'./audio/audioten.wav'},
	{y:311,audioname:"audio11",file:'./audio/audio11.wav'},
	{y:312,audioname:"audio12",file:'./audio/audio12.wav'},
	{y:313,audioname:"audio13",file:'./audio/audio13.wav'},
	{y:314,audioname:"audio14",file:'./audio/audio14.wav'},
	{y:315,audioname:"audio15",file:'./audio/audio15.wav'},
	{y:316,audioname:"audio16",file:'./audio/audio16.wav'},
	{y:317,audioname:"audio17",file:'./audio/audio17.wav'},
	{y:318,audioname:"audio18",file:'./audio/audio18.wav'},
	{y:319,audioname:"audio19",file:'./audio/audio19.wav'},
	{y:320,audioname:"audio20",file:'./audio/audio20.wav'},
	{y:321,audioname:"audio21",file:'./audio/audio21.wav'},
	{y:322,audioname:"audiotwo",file:'./audio/audiotwo.wav'},
	{y:323,audioname:"audiothree",file:'./audio/audiothree.wav'},
	{y:324,audioname:"audiofour",file:'./audio/audiofour.wav'},
	{y:325,audioname:"audiofive",file:'./audio/audiofive.wav'},
	{y:326,audioname:"audiosix",file:'./audio/audiosix.wav'},
	{y:327,audioname:"audioseven",file:'./audio/audioseven.wav'},
	{y:328,audioname:"audioeight",file:'./audio/audioeight.wav'},
	{y:329,audioname:"audionine",file:'./audio/audionine.wav'},
	{y:330,audioname:"audioten",file:'./audio/audioten.wav'},
	{y:331,audioname:"audioone",file:'./audio/audioone.wav'},
	{y:332,audioname:"audiotwo",file:'./audio/audiotwo.wav'},
	{y:333,audioname:"audiothree",file:'./audio/audiothree.wav'},
	{y:334,audioname:"audiofour",file:'./audio/audiofour.wav'},
	{y:335,audioname:"audiofive",file:'./audio/audiofive.wav'},
	{y:336,audioname:"audiosix",file:'./audio/audiosix.wav'},
	{y:337,audioname:"audioseven",file:'./audio/audioseven.wav'},
	{y:338,audioname:"audioeight",file:'./audio/audioeight.wav'},
	{y:339,audioname:"audionine",file:'./audio/audionine.wav'},
	{y:340,audioname:"audioten",file:'./audio/audioten.wav'},
	{y:341,audioname:"audio11",file:'./audio/audio11.wav'},
	{y:342,audioname:"audio12",file:'./audio/audio12.wav'},
	{y:343,audioname:"audio13",file:'./audio/audio13.wav'},
	{y:344,audioname:"audio14",file:'./audio/audio14.wav'},
	{y:345,audioname:"audio15",file:'./audio/audio15.wav'},
	{y:346,audioname:"audio16",file:'./audio/audio16.wav'},
	{y:347,audioname:"audio17",file:'./audio/audio17.wav'},
	{y:348,audioname:"audio18",file:'./audio/audio18.wav'},
	{y:349,audioname:"audio19",file:'./audio/audio19.wav'},
	{y:350,audioname:"audio20",file:'./audio/audio20.wav'},
	{y:351,audioname:"audioone",file:'./audio/audioone.wav'},
	{y:352,audioname:"audiotwo",file:'./audio/audiotwo.wav'},
	{y:353,audioname:"audiothree",file:'./audio/audiothree.wav'},
	{y:354,audioname:"audiofour",file:'./audio/audiofour.wav'},
	{y:355,audioname:"audiofive",file:'./audio/audiofive.wav'},
	{y:356,audioname:"audiosix",file:'./audio/audiosix.wav'},
	{y:357,audioname:"audioseven",file:'./audio/audioseven.wav'},
	{y:358,audioname:"audioeight",file:'./audio/audioeight.wav'},
	{y:359,audioname:"audionine",file:'./audio/audionine.wav'},
	{y:360,audioname:"audioten",file:'./audio/audioten.wav'},
	{y:361,audioname:"audio11",file:'./audio/audio11.wav'},
	{y:362,audioname:"audio12",file:'./audio/audio12.wav'},
	{y:363,audioname:"audio13",file:'./audio/audio13.wav'},
	{y:364,audioname:"audio14",file:'./audio/audio14.wav'},
	{y:365,audioname:"audio15",file:'./audio/audio15.wav'},
	{y:366,audioname:"audio16",file:'./audio/audio16.wav'},
	{y:367,audioname:"audio17",file:'./audio/audio17.wav'},
	{y:368,audioname:"audio18",file:'./audio/audio18.wav'},
	{y:369,audioname:"audio19",file:'./audio/audio19.wav'},
	{y:370,audioname:"audio20",file:'./audio/audio20.wav'},
	{y:371,audioname:"audio21",file:'./audio/audio21.wav'},
	{y:372,audioname:"audiotwo",file:'./audio/audiotwo.wav'},
	{y:373,audioname:"audiothree",file:'./audio/audiothree.wav'},
	{y:374,audioname:"audiofour",file:'./audio/audiofour.wav'},
	{y:375,audioname:"audiofive",file:'./audio/audiofive.wav'},
	{y:376,audioname:"audiosix",file:'./audio/audiosix.wav'},
	{y:377,audioname:"audioseven",file:'./audio/audioseven.wav'},
	{y:378,audioname:"audioeight",file:'./audio/audioeight.wav'},
	{y:379,audioname:"audionine",file:'./audio/audionine.wav'},
	{y:380,audioname:"audioten",file:'./audio/audioten.wav'},
	{y:381,audioname:"audioone",file:'./audio/audioone.wav'},
	{y:382,audioname:"audiotwo",file:'./audio/audiotwo.wav'},
	{y:383,audioname:"audiothree",file:'./audio/audiothree.wav'},
	{y:384,audioname:"audiofour",file:'./audio/audiofour.wav'},
	{y:385,audioname:"audiofive",file:'./audio/audiofive.wav'},
	{y:386,audioname:"audiosix",file:'./audio/audiosix.wav'},
	{y:387,audioname:"audioseven",file:'./audio/audioseven.wav'},
	{y:388,audioname:"audioeight",file:'./audio/audioeight.wav'},
	{y:389,audioname:"audionine",file:'./audio/audionine.wav'},
	{y:390,audioname:"audioten",file:'./audio/audioten.wav'},
	{y:391,audioname:"audio11",file:'./audio/audio11.wav'},
	{y:392,audioname:"audio12",file:'./audio/audio12.wav'},
	{y:393,audioname:"audio13",file:'./audio/audio13.wav'},
	{y:394,audioname:"audio14",file:'./audio/audio14.wav'},
	{y:395,audioname:"audio15",file:'./audio/audio15.wav'},
	{y:396,audioname:"audio16",file:'./audio/audio16.wav'},
	{y:397,audioname:"audio17",file:'./audio/audio17.wav'},
	{y:398,audioname:"audio18",file:'./audio/audio18.wav'},
	{y:399,audioname:"audio19",file:'./audio/audio19.wav'},
	{y:400,audioname:"audio20",file:'./audio/audio20.wav'},



	{y:401,audioname:"audioone",file:'./audio/audioone.wav'},
	{y:402,audioname:"audiotwo",file:'./audio/audiotwo.wav'},
	{y:403,audioname:"audiothree",file:'./audio/audiothree.wav'},
	{y:404,audioname:"audiofour",file:'./audio/audiofour.wav'},
	{y:405,audioname:"audiofive",file:'./audio/audiofive.wav'},
	{y:406,audioname:"audiosix",file:'./audio/audiosix.wav'},
	{y:407,audioname:"audioseven",file:'./audio/audioseven.wav'},
	{y:408,audioname:"audioeight",file:'./audio/audioeight.wav'},
	{y:409,audioname:"audionine",file:'./audio/audionine.wav'},
	{y:410,audioname:"audioten",file:'./audio/audioten.wav'},
	{y:411,audioname:"audio11",file:'./audio/audio11.wav'},
	{y:412,audioname:"audio12",file:'./audio/audio12.wav'},
	{y:413,audioname:"audio13",file:'./audio/audio13.wav'},
	{y:414,audioname:"audio14",file:'./audio/audio14.wav'},
	{y:415,audioname:"audio15",file:'./audio/audio15.wav'},
	{y:416,audioname:"audio16",file:'./audio/audio16.wav'},
	{y:417,audioname:"audio17",file:'./audio/audio17.wav'},
	{y:418,audioname:"audio18",file:'./audio/audio18.wav'},
	{y:419,audioname:"audio19",file:'./audio/audio19.wav'},
	{y:420,audioname:"audio20",file:'./audio/audio20.wav'},
	{y:421,audioname:"audio21",file:'./audio/audio21.wav'},
	{y:422,audioname:"audiotwo",file:'./audio/audiotwo.wav'},
	{y:423,audioname:"audiothree",file:'./audio/audiothree.wav'},
	{y:424,audioname:"audiofour",file:'./audio/audiofour.wav'},
	{y:425,audioname:"audiofive",file:'./audio/audiofive.wav'},
	{y:426,audioname:"audiosix",file:'./audio/audiosix.wav'},
	{y:427,audioname:"audioseven",file:'./audio/audioseven.wav'},
	{y:428,audioname:"audioeight",file:'./audio/audioeight.wav'},
	{y:429,audioname:"audionine",file:'./audio/audionine.wav'},
	{y:430,audioname:"audioten",file:'./audio/audioten.wav'},
	{y:431,audioname:"audioone",file:'./audio/audioone.wav'},
	{y:432,audioname:"audiotwo",file:'./audio/audiotwo.wav'},
	{y:433,audioname:"audiothree",file:'./audio/audiothree.wav'},
	{y:434,audioname:"audiofour",file:'./audio/audiofour.wav'},
	{y:435,audioname:"audiofive",file:'./audio/audiofive.wav'},
	{y:436,audioname:"audiosix",file:'./audio/audiosix.wav'},
	{y:437,audioname:"audioseven",file:'./audio/audioseven.wav'},
	{y:438,audioname:"audioeight",file:'./audio/audioeight.wav'},
	{y:439,audioname:"audionine",file:'./audio/audionine.wav'},
	{y:440,audioname:"audioten",file:'./audio/audioten.wav'},
	{y:441,audioname:"audio11",file:'./audio/audio11.wav'},
	{y:442,audioname:"audio12",file:'./audio/audio12.wav'},
	{y:443,audioname:"audio13",file:'./audio/audio13.wav'},
	{y:444,audioname:"audio14",file:'./audio/audio14.wav'},
	{y:445,audioname:"audio15",file:'./audio/audio15.wav'},
	{y:446,audioname:"audio16",file:'./audio/audio16.wav'},
	{y:447,audioname:"audio17",file:'./audio/audio17.wav'},
	{y:448,audioname:"audio18",file:'./audio/audio18.wav'},
	{y:449,audioname:"audio19",file:'./audio/audio19.wav'},
	{y:450,audioname:"audio20",file:'./audio/audio20.wav'},
	{y:451,audioname:"audioone",file:'./audio/audioone.wav'},
	{y:452,audioname:"audiotwo",file:'./audio/audiotwo.wav'},
	{y:453,audioname:"audiothree",file:'./audio/audiothree.wav'},
	{y:454,audioname:"audiofour",file:'./audio/audiofour.wav'},
	{y:455,audioname:"audiofive",file:'./audio/audiofive.wav'},
	{y:456,audioname:"audiosix",file:'./audio/audiosix.wav'},
	{y:457,audioname:"audioseven",file:'./audio/audioseven.wav'},
	{y:458,audioname:"audioeight",file:'./audio/audioeight.wav'},
	{y:459,audioname:"audionine",file:'./audio/audionine.wav'},
	{y:460,audioname:"audioten",file:'./audio/audioten.wav'},
	{y:461,audioname:"audio11",file:'./audio/audio11.wav'},
	{y:462,audioname:"audio12",file:'./audio/audio12.wav'},
	{y:463,audioname:"audio13",file:'./audio/audio13.wav'},
	{y:464,audioname:"audio14",file:'./audio/audio14.wav'},
	{y:465,audioname:"audio15",file:'./audio/audio15.wav'},
	{y:466,audioname:"audio16",file:'./audio/audio16.wav'},
	{y:467,audioname:"audio17",file:'./audio/audio17.wav'},
	{y:468,audioname:"audio18",file:'./audio/audio18.wav'},
	{y:469,audioname:"audio19",file:'./audio/audio19.wav'},
	{y:470,audioname:"audio20",file:'./audio/audio20.wav'},
	{y:471,audioname:"audio21",file:'./audio/audio21.wav'},
	{y:472,audioname:"audiotwo",file:'./audio/audiotwo.wav'},
	{y:473,audioname:"audiothree",file:'./audio/audiothree.wav'},
	{y:474,audioname:"audiofour",file:'./audio/audiofour.wav'},
	{y:475,audioname:"audiofive",file:'./audio/audiofive.wav'},
	{y:476,audioname:"audiosix",file:'./audio/audiosix.wav'},
	{y:477,audioname:"audioseven",file:'./audio/audioseven.wav'},
	{y:478,audioname:"audioeight",file:'./audio/audioeight.wav'},
	{y:479,audioname:"audionine",file:'./audio/audionine.wav'},
	{y:480,audioname:"audioten",file:'./audio/audioten.wav'},
	{y:481,audioname:"audioone",file:'./audio/audioone.wav'},
	{y:482,audioname:"audiotwo",file:'./audio/audiotwo.wav'},
	{y:483,audioname:"audiothree",file:'./audio/audiothree.wav'},
	{y:484,audioname:"audiofour",file:'./audio/audiofour.wav'},
	{y:485,audioname:"audiofive",file:'./audio/audiofive.wav'},
	{y:486,audioname:"audiosix",file:'./audio/audiosix.wav'},
	{y:487,audioname:"audioseven",file:'./audio/audioseven.wav'},
	{y:488,audioname:"audioeight",file:'./audio/audioeight.wav'},
	{y:489,audioname:"audionine",file:'./audio/audionine.wav'},
	{y:490,audioname:"audioten",file:'./audio/audioten.wav'},
	{y:491,audioname:"audio11",file:'./audio/audio11.wav'},
	{y:492,audioname:"audio12",file:'./audio/audio12.wav'},
	{y:493,audioname:"audio13",file:'./audio/audio13.wav'},
	{y:494,audioname:"audio14",file:'./audio/audio14.wav'},
	{y:495,audioname:"audio15",file:'./audio/audio15.wav'},
	{y:496,audioname:"audio16",file:'./audio/audio16.wav'},
	{y:497,audioname:"audio17",file:'./audio/audio17.wav'},
	{y:498,audioname:"audio18",file:'./audio/audio18.wav'},
	{y:499,audioname:"audio19",file:'./audio/audio19.wav'},
	{y:500,audioname:"audio20",file:'./audio/audio20.wav'},
	
	{y:501,audioname:"audioone",file:'./audio/audioone.wav'},
	{y:502,audioname:"audiotwo",file:'./audio/audiotwo.wav'},
	{y:503,audioname:"audiothree",file:'./audio/audiothree.wav'},
	{y:504,audioname:"audiofour",file:'./audio/audiofour.wav'},
	{y:505,audioname:"audiofive",file:'./audio/audiofive.wav'},
	{y:506,audioname:"audiosix",file:'./audio/audiosix.wav'},
	{y:507,audioname:"audioseven",file:'./audio/audioseven.wav'},
	{y:508,audioname:"audioeight",file:'./audio/audioeight.wav'},
	{y:509,audioname:"audionine",file:'./audio/audionine.wav'},
	{y:510,audioname:"audioten",file:'./audio/audioten.wav'},
	{y:511,audioname:"audio11",file:'./audio/audio11.wav'},
	{y:512,audioname:"audio12",file:'./audio/audio12.wav'},
	{y:513,audioname:"audio13",file:'./audio/audio13.wav'},
	{y:514,audioname:"audio14",file:'./audio/audio14.wav'},
	{y:515,audioname:"audio15",file:'./audio/audio15.wav'},
	{y:516,audioname:"audio16",file:'./audio/audio16.wav'},
	{y:517,audioname:"audio17",file:'./audio/audio17.wav'},
	{y:518,audioname:"audio18",file:'./audio/audio18.wav'},
	{y:519,audioname:"audio19",file:'./audio/audio19.wav'},
	{y:520,audioname:"audio20",file:'./audio/audio20.wav'},
	{y:521,audioname:"audio21",file:'./audio/audio21.wav'},
	{y:522,audioname:"audiotwo",file:'./audio/audiotwo.wav'},
	{y:523,audioname:"audiothree",file:'./audio/audiothree.wav'},
	{y:524,audioname:"audiofour",file:'./audio/audiofour.wav'},
	{y:525,audioname:"audiofive",file:'./audio/audiofive.wav'},
	{y:526,audioname:"audiosix",file:'./audio/audiosix.wav'},
	{y:527,audioname:"audioseven",file:'./audio/audioseven.wav'},
	{y:528,audioname:"audioeight",file:'./audio/audioeight.wav'},
	{y:529,audioname:"audionine",file:'./audio/audionine.wav'},
	{y:530,audioname:"audioten",file:'./audio/audioten.wav'},
	{y:531,audioname:"audioone",file:'./audio/audioone.wav'},
	{y:532,audioname:"audiotwo",file:'./audio/audiotwo.wav'},
	{y:533,audioname:"audiothree",file:'./audio/audiothree.wav'},
	{y:534,audioname:"audiofour",file:'./audio/audiofour.wav'},
	{y:535,audioname:"audiofive",file:'./audio/audiofive.wav'},
	{y:536,audioname:"audiosix",file:'./audio/audiosix.wav'},
	{y:537,audioname:"audioseven",file:'./audio/audioseven.wav'},
	{y:538,audioname:"audioeight",file:'./audio/audioeight.wav'},
	{y:539,audioname:"audionine",file:'./audio/audionine.wav'},
	{y:540,audioname:"audioten",file:'./audio/audioten.wav'},
	{y:541,audioname:"audio11",file:'./audio/audio11.wav'},
	{y:542,audioname:"audio12",file:'./audio/audio12.wav'},
	{y:543,audioname:"audio13",file:'./audio/audio13.wav'},
	{y:544,audioname:"audio14",file:'./audio/audio14.wav'},
	{y:545,audioname:"audio15",file:'./audio/audio15.wav'},
	{y:546,audioname:"audio16",file:'./audio/audio16.wav'},
	{y:547,audioname:"audio17",file:'./audio/audio17.wav'},
	{y:548,audioname:"audio18",file:'./audio/audio18.wav'},
	{y:549,audioname:"audio19",file:'./audio/audio19.wav'},
	{y:550,audioname:"audio20",file:'./audio/audio20.wav'},
	{y:551,audioname:"audioone",file:'./audio/audioone.wav'},
	{y:552,audioname:"audiotwo",file:'./audio/audiotwo.wav'},
	{y:553,audioname:"audiothree",file:'./audio/audiothree.wav'},
	{y:554,audioname:"audiofour",file:'./audio/audiofour.wav'},
	{y:555,audioname:"audiofive",file:'./audio/audiofive.wav'},
	{y:556,audioname:"audiosix",file:'./audio/audiosix.wav'},
	{y:557,audioname:"audioseven",file:'./audio/audioseven.wav'},
	{y:558,audioname:"audioeight",file:'./audio/audioeight.wav'},
	{y:559,audioname:"audionine",file:'./audio/audionine.wav'},
	{y:560,audioname:"audioten",file:'./audio/audioten.wav'},
	{y:561,audioname:"audio11",file:'./audio/audio11.wav'},
	{y:562,audioname:"audio12",file:'./audio/audio12.wav'},
	{y:563,audioname:"audio13",file:'./audio/audio13.wav'},
	{y:564,audioname:"audio14",file:'./audio/audio14.wav'},
	{y:565,audioname:"audio15",file:'./audio/audio15.wav'},
	{y:566,audioname:"audio16",file:'./audio/audio16.wav'},
	{y:567,audioname:"audio17",file:'./audio/audio17.wav'},
	{y:568,audioname:"audio18",file:'./audio/audio18.wav'},
	{y:569,audioname:"audio19",file:'./audio/audio19.wav'},
	{y:570,audioname:"audio20",file:'./audio/audio20.wav'},
	{y:571,audioname:"audio21",file:'./audio/audio21.wav'},
	{y:572,audioname:"audiotwo",file:'./audio/audiotwo.wav'},
	{y:573,audioname:"audiothree",file:'./audio/audiothree.wav'},
	{y:574,audioname:"audiofour",file:'./audio/audiofour.wav'},
	{y:575,audioname:"audiofive",file:'./audio/audiofive.wav'},
	{y:576,audioname:"audiosix",file:'./audio/audiosix.wav'},
	{y:577,audioname:"audioseven",file:'./audio/audioseven.wav'},
	{y:578,audioname:"audioeight",file:'./audio/audioeight.wav'},
	{y:579,audioname:"audionine",file:'./audio/audionine.wav'},
	{y:580,audioname:"audioten",file:'./audio/audioten.wav'},
	{y:581,audioname:"audioone",file:'./audio/audioone.wav'},
	{y:582,audioname:"audiotwo",file:'./audio/audiotwo.wav'},
	{y:583,audioname:"audiothree",file:'./audio/audiothree.wav'},
	{y:584,audioname:"audiofour",file:'./audio/audiofour.wav'},
	{y:585,audioname:"audiofive",file:'./audio/audiofive.wav'},
	{y:586,audioname:"audiosix",file:'./audio/audiosix.wav'},
	{y:587,audioname:"audioseven",file:'./audio/audioseven.wav'},
	{y:588,audioname:"audioeight",file:'./audio/audioeight.wav'},
	{y:589,audioname:"audionine",file:'./audio/audionine.wav'},
	{y:590,audioname:"audioten",file:'./audio/audioten.wav'},
	{y:591,audioname:"audio11",file:'./audio/audio11.wav'},
	{y:592,audioname:"audio12",file:'./audio/audio12.wav'},
	{y:593,audioname:"audio13",file:'./audio/audio13.wav'},
	{y:594,audioname:"audio14",file:'./audio/audio14.wav'},
	{y:595,audioname:"audio15",file:'./audio/audio15.wav'},
	{y:596,audioname:"audio16",file:'./audio/audio16.wav'},
	{y:597,audioname:"audio17",file:'./audio/audio17.wav'},
	{y:598,audioname:"audio18",file:'./audio/audio18.wav'},
	{y:599,audioname:"audio19",file:'./audio/audio19.wav'},
	{y:600,audioname:"audio20",file:'./audio/audio20.wav'},
]
// console.log(window.screen.availWidth)


const rec=[]
window.onload = function () {
  var selectCanvas = document.getElementById("myCanvas");
  var brushPalette = document.getElementById("brushPalette");
  var w = window.innerWidth;
  const canvas=document.getElementById("myCanvas")
  canvas.width=w
 
  console.log(canvas)
//   console.log(w)

  
  if (selectCanvas) {
    selectCanvas.addEventListener("mousedown", start, false);
    selectCanvas.addEventListener("mouseup", stop, false);
    selectCanvas.addEventListener("mousemove", draw, false);
    brushPalette.addEventListener(
      "click",
      function (e) {
        changeStroke(e, this);
      },
      false
    );

    var isDown = false;
    var context = selectCanvas.getContext("2d");
    var canvasX, canvasY;
    context.lineWidth = 2;

    function start(e) {
      isDown = true;
      context.beginPath();
      canvasX = e.pageX - selectCanvas.offsetLeft;
      canvasY = e.pageY - selectCanvas.offsetTop;
      context.moveTo(canvasX, canvasY);
    }

    function draw(e) {
      
      if (isDown) {
		
        console.log(e);
		
        canvasX = e.pageX - selectCanvas.offsetLeft;
        canvasY = e.pageY - selectCanvas.offsetTop;
        context.lineTo(canvasX, canvasY);
        context.strokeStyle = selectedColor.value;
        context.stroke();
		console.log(canvasX)
		console.log(canvasY)
		arr.forEach(element => {
			if(element.y == canvasY){
			console.log(element.audioname)
			
			var x = document.getElementById(element.audioname);
			rec.push(element.audioname)
			console.log(rec)
		
			x.play()
		}
		else{

		}
		});
	
	
      }
    }
	
    function stop(e) {
      isDown = false;
      context.closePath();
    }

    function changeStroke(e, obj) {
      if (e.target.dataset.stroke) {
        var parent = e.target.parentElement.children;
        for (var i in parent) {
          if (parent.hasOwnProperty(i)) {
            if (e.target.className === parent[i].className) {
              e.target.style.border = "2px dotted";
            } else {
              parent[i].style.border = "none";
            }
          }
        }
        context.lineWidth = e.target.dataset.stroke;
      }
    }
  }
};
function playrec() {
	// var audio = document.getElementById("audio");
	// audio.play();
	const arr = [1,2,3,4,5];
const delay = 500;
              
rec.forEach(
    (el, i) => {
      setTimeout(() => 
	 {
		var x = document.getElementById(el);
		x.play()
		console.log("i",i)
		console.log(el)
	 } 
	
	  , delay * i);
    }
);
	
  }

  function reload() {
	var selectCanvas = document.getElementById("myCanvas");
	const canvas=document.getElementById("myCanvas")
	var w = window.innerWidth;
	canvas.width=w

	selectCanvas.getContext(0, 0, canvas.width)
  }